### ISSUE TITLE
Convert i18n files to JSON

### ISSUE THREAD

**Issue by siebrand** [Krinkle/intuition#10]
Allows easier usage in other languages than PHP, too.

**Comment by Krinkle** [comment]
@siebrand I'll get on this coming weekend. What would it require from your end to switch to JSON? I'd prefer a directory structure like `/i18n/{domain}/{lang}.json`. I'm flexible though. Whatever is most convenient for translatewiki.net!

**Comment by zhaofengli** [comment]
@Krinkle Is there any possibility that you get #34 done? It's been more than a month. Thank you.

**Comment by siebrand** [comment]
@Krinkle That structure is excellent. Will you be converting everything, or would you like us/me to just export in the new format?

**Comment by Krinkle** [comment]
@siebrand I don't need the files while implementing, but let's work in parallel. Could you do an export using the new format in a branch? I'll be sure to squash that branch into my commit once done. Let's hold off on localisation updates while we work on this (until Monday?).

**Comment by siebrand** [comment]
Done: https://github.com/Krinkle/intuition/commit/64ae01a80c118c3ba67c00a3125c3056f74ad1df

Enjoy!

Related MediaWiki and translatewiki.net patches (currently active):
* Translate: https://gerrit.wikimedia.org/r/#/c/191687/
* translatewiki: https://gerrit.wikimedia.org/r/#/c/191689/

 I've disabled Intuition updates and exports until you commit this to the master branch, @Krinkle.

**Comment by Krinkle** [comment]
@siebrand Thanks!

Can we change the directory name to be lowercase? Or (as currently) ucfirst(lowercase). Right now the migration commit changes them to expose the casing of the tool's display title which I can't know from the domain identifier (which is case-insensitive).

Basically in `Translate:/ffs/IntuitionTextdomains.php`, use `$sanitizedName` directly instead of filtered `$name`. Should make things easier for you as well I hope.

**Comment by siebrand** [comment]
>
> Can we change the directory name to be lowercase? Or (as currently)
> ucfirst(lowercase). Right now the migration commit changes them to expose
> the casing of the tool's display title which I can't know from the domain
> identifier (which is case-insensitive).
>
Done.

**Comment by Krinkle** [comment]
Thanks! Implementing it now.

**Comment by Krinkle** [comment]
@siebrand In ff512c531998 there is a strange `%code%.json` file in `messages/tsintuition/`.

**Comment by Krinkle** [comment]
Looks like @Nikerabbit fixed that in wikimedia/translatewiki@b99208ed7711c108e80f10643bbf010bb6a805a4.

**Comment by ricordisamoa** [comment]
I'd like to enhance some of my non-PHP tools with the help of translatewiki.
Is it feasible to use Intuition itself or should I reinvent the wheel?

**Comment by Krinkle** [comment]
@Nikerabbit @siebrand It's still broken unfortunately. The first time `tsintuition` was exported in a single file literally called `%code%.json` (branch: [json-i18n](https://github.com/Krinkle/intuition/tree/ff512c5319981303b89ce2c9ab9015805083a6bc/language/messages/tsintuition)). The second time (after wikimedia/translatewiki@b99208e), is missing the tsintuition directory entirely (branch: [json-i18n2](https://github.com/Krinkle/intuition/tree/83b5336d832c6979c204387f5eaf7cebb0cad182/language/messages)).

**Comment by Krinkle** [comment]
The implementation is ready and tests are passing. However there's still a few domains missing: `reflinks`, `wlm`, and `wlmsurvey`. These not yet imported. I've added them to the group in https://gerrit.wikimedia.org/r/205073.

**Comment by siebrand** [comment]
Should all be fine now in branch json-i18n.

**Comment by Nikerabbit** [comment]
FYI: I updated json-i18n2 last week after Krinkle poked me on IRC.

**Comment by Krinkle** [comment]
The conversion has landed. Big thanks to @Nikerabbit and @siebrand! :star2:
