### ISSUE TITLE
Remove ToolStart.php entry point

### ISSUE THREAD

**Issue by Krinkle** [Krinkle/intuition#101]
Once existing usage has been removed from Wikimedia Toolforge tool, this can be removed.

This is part of the deprecated interface whereby tools include `/data/project/intuition` directly on Toolforge, and does not relate to the composer package (for which removal would be less controversial as existing users wouldn't be affected given they would need to upgrade first).

**Comment by Krinkle** [comment]
Per legacy documentation at <https://github.com/Krinkle/intuition/wiki/Documentation/4065f84748e7ac21303af215f2ddf3fb5b6d255d>, Toolforge tool authors that use ToolStart.php will likely contain the phrase `Intuition/ToolStart.php` somewhere in the tool's code.

**Comment by Krinkle** [comment]
Thanks to @bd808, we've now got a list of tools to work from at <https://phabricator.wikimedia.org/P7852>. I have reduced the results to only matches without `vendor/composer/auto` (false positives, unrelated), and included it below as checklist:

* [ ] `./etwikibots/public_html/common/lib.php`
* [ ] `./hotarticles/public_html/pageviews/public_html/_head2.php`
* [ ] `./jarry-common/public_html/i18n.php`
* [ ] `./jarry-common/public_html/libs/i18n.php`
* [ ] `./langviews/_head.php`
* [ ] `./langviews/public_html/_head.php`
* [ ] `./langviews-test/_head.php`
* [ ] `./langviews-test/public_html/_head.php`
* [ ] `./list/src/wmf-tool-list/lib/basetool/LocalConfig-krinkledev.php`
* [ ] `./list/src/wmf-tool-list/lib/basetool/LocalConfig.php`
* [ ] `./list/src/wmf-tool-list/lib/basetool/LocalConfig-wmflabs-intuition.php`
* [ ] `./list/src/wmf-tool-list/lib/basetool/sample-toollabs-LocalConfig.php`
* [ ] `./massviews/_head.php`
* [ ] `./massviews/public_html/_head.php`
* [ ] `./massviews-test/_head.php`
* [ ] `./massviews-test/public_html/_head.php`
* [ ] `./mc8/public_html/shared.php`
* [ ] `./mediaviews/_head.php`
* [ ] `./mediaviews/public_html/_head.php`
* [ ] `./metaviews/_head.php`
* [ ] `./metaviews/public_html/_head.php`
* [ ] `./meta/xtools/modules/WebTool.php`
* [ ] `./newwebtest/xtools_old/public_html/WebTool.php`
* [ ] `./newwebtest/xtools/public_html/WebTool.php`
* [ ] `./pageviews/_head.php`
* [ ] `./pageviews/public_html/_head.php`
* [ ] `./pageviews-test/_head.php`
* [ ] `./pageviews-test/public_html/_head.php`
* [ ] `./raun/Raun/index.php`
* [ ] `./raun/Raun/index-rewrite.php`
* [ ] `./redirectviews/_head.php`
* [ ] `./redirectviews/public_html/_head.php`
* [ ] `./refill/versions/stable/config/config.backup.php`
* [ ] `./siteviews/_head.php`
* [ ] `./siteviews/public_html/_head.php`
* [ ] `./templatetransclusioncheck/public_html/index2.php`
* [ ] `./templatetransclusioncheck/public_html/index.php`
* [ ] `./templatetransclusioncheck/public_html/test/index.php`
* [ ] `./topviews/_head.php`
* [ ] `./topviews/public_html/_head.php`
* [ ] `./topviews-test/_head.php`
* [ ] `./topviews-test/public_html/_head.php`
* [ ] `./tour/git/wmf-tool-tour/vendor/krinkle/toollabs-base/LocalConfig-krinkledev.php`
* [ ] `./tour/git/wmf-tool-tour/vendor/krinkle/toollabs-base/LocalConfig.php`
* [ ] `./tour/git/wmf-tool-tour/vendor/krinkle/toollabs-base/LocalConfig-wmflabs-intuition.php`
* [ ] `./tour/git/wmf-tool-tour/vendor/krinkle/toollabs-base/sample-toollabs-LocalConfig.php`
* [ ] `./tsreports-dev/src/intuition/libs/basetool/LocalConfig-krinkledev.php`
* [ ] `./tsreports-dev/src/intuition/libs/basetool/LocalConfig-wmflabs-intuition.php`
* [ ] `./tsreports-dev/src/intuition/libs/basetool/sample-toollabs-LocalConfig.php`
* [ ] `./userviews/_head.php`
* [ ] `./userviews/pageviews/public_html/_head.php`
* [ ] `./userviews/public_html/_head.php`
* [ ] `./wikiinfo/src/wmf-tool-wikiinfo/vendor/krinkle/toollabs-base/LocalConfig-krinkledev.php`
* [ ] `./wikiinfo/src/wmf-tool-wikiinfo/vendor/krinkle/toollabs-base/LocalConfig-wmflabs-intuition.php`
* [ ] `./wikiinfo/src/wmf-tool-wikiinfo/vendor/krinkle/toollabs-base/sample-toollabs-LocalConfig.php`
* [ ] `./wikiviewstats2/dev/functions.php`
* [ ] `./wikiviewstats2/dev/TsIntuition/includes/libs/ts-krinkle-basetool/sample-LocalConfig.php`
* [ ] `./wikiviewstats2/intuition/includes/libs/basetool/sample-LocalConfig.php`
* [ ] `./wikiviewstats2/wvs_modules/I18n.php`
* [ ] `./wikiviewstats/wvs_modules/I18n.php`
* [ ] `./xstools/modules/WebTool.php`
* [ ] `./xtools-articleinfo/modules/WebTool.php`
* [ ] `./xtools-mab-dev/modules/WebTool.php`
* [ ] `./xtools/modules/WebTool-backup.php`
* [ ] `./xtools/modules/WebTool.php`
* [ ] `./xtools-pages/vendor/composer/autoload_static.php`

**Comment by Krinkle** [comment]
@MusikAnimal Could you take a look at the pageviews-related entries?

From what I can tell these tools no longer use messages from the library, which means it should be fairly straight-forward to load the library from composer instead.

**Comment by Krinkle** [comment]
I've e-mailed the following maintainers:

* Kentaur at Wikitech (for `etwikibots`),
* Kaldari at Wikitech (for `hotarticles`),
* Jarry1250 at Wikitech (for `jarry-common`),
* Microchip08 at Wikitech  (for `mc8`),
* Kenrick95 at Wikitech (for `raun`),
* Chameleon at no:User:Chameleon222 (for `templatetransclusioncheck`).

**Comment by kenrick95** [comment]
Hi @Krinkle , thanks for the notice!

For "raun", these two files that you mentioned are located in a folder that's no longer in use by the tool. So I just removed that folder from Toolforge. 😁 

Thanks!

**Comment by Krinkle** [comment]
Perfect. I've checked it off the list. Thanks @kenrick95!

**Comment by Krinkle** [comment]
I've frozen the shared installation at `/data/project/intuition` to v0.7.0.

This means it is now safe to remove the deprecated ToolStart.php or break PHP5 support in new releases, because this legacy entry point on the Toolforge will stay exactly as it is today.
