### ISSUE TITLE
Typo in Github Wiki Documentation

### ISSUE THREAD

**Issue by Xi-Plus** [Krinkle/intuition#105]
https://github.com/Krinkle/intuition/wiki/Documentation#getlangname
Lang functions / getLangName / Arguments
`$lang` (string): Language code of language to get ~fallback for~.
Should be
`$lang` (string): Language code of language to get name.

**Comment by Krinkle** [comment]
@Xi-Plus [Fixed](https://github.com/Krinkle/intuition/wiki/Documentation/_compare/09b443eef56092076329c83cb3c7f4c13d2d6b87...a29fb5be8d0103346c57b739d000ee569137fd7a).

Thank you!
