### ISSUE TITLE
VoiceIntro not showing on TranslateWiki.net

### ISSUE THREAD

**Issue by Jarry1250** [Krinkle/intuition#13]
Three weeks ago the VoiceIntro project was added to TsIntuition in [1], but it's not showing on TranslateWiki.net . What needs to happen to 'make it so'?

[1] https://github.com/Krinkle/TsIntuition/commit/ff3191c01eb469214c025404c26f0d090d18005d

**Comment by Nikerabbit** [comment]
I see Voiceintro at translatewiki.net now.
