### ISSUE TITLE
Questions concerning the workflow

### ISSUE THREAD

**Issue by Hedonil** [Krinkle/intuition#27]
Sometimes there's a certain lag in accessing new language messages.
Translatewiki.net --> Intuition Repo GitHub --> Intuition src on Tool Labs
The latter is the source for the tool (if you don't want to rely permanently on your own textfile)
Is this an automated process (all 3 steps), or is this done by hand? 
It would be great, if these steps - and the merge of new tool domains/messages - would happen in a fixed period. This would make things more predictable.
Eg.: message updates from TWN every day (two/three days?), merges not later than a week and GitHub repo synced to Tool Labs every day.
Thanks.

**Comment by Krinkle** [comment]
You may also be interested in #45 and 75cfbc25a.
