### ISSUE TITLE
Support storing messages in individual tool repos

### ISSUE THREAD

**Issue by Krinkle** [Krinkle/intuition#45]
We currently store messages inside the Intuition project. This is very different from other software projects, e.g. MediaWiki extensions and other projects translated by translatewiki.net.

A project should be alllowed to store the `i18n/` directory in their own git repository. This makes it easier for them to change the English source messages.

Moving messages to other repos adds complexity and responsibility for tool authors:

* Tool authors will have to store their program in public version control on GitHub or Gerrit.
* Tool authors will have to register each of their tools with translatewiki.net directly, so that translatewiki can import messages and export translations.
* Tool authors will have to authorise translatewiki.net commit access to their repository.
* Tool authors will have to make sure their tool is frequently updated so that translations are deployed in a timely manner.

If tools become independent, then there will be increased workload for translatewiki.net. We may be able to keep them categorised as domains inside "Intuition". Instead of having their own top-level namespace at translatewiki (by using prefixes, like we do already). Messages need to pushed to separate repositories.

Intuition itself is generic and re-usable and doesn't require domains to come from its own repository. As demonstrated by #42, it can be used to fetch messages from anywhere (e.g. your own repository) and still make use if its features.

This issue tracks the following two tasks:
* Coordinate with translatewiki and verify it is acceptable to have these registered as their own project.
* Move one project as example (e.g. I can move orphantalk messages to the OrphanTalk repo).
* Improve Intuition PHP interface to make it easier to load messages from a custom directory.

**Comment by nemobis** [comment]
Letting maintainers optionally use the Intuition framework (and translatewiki.net project?) is something that can only do good.

There is perhaps a middle way? For instance
* a service to fetch updates to sync messages automatically from the source repositories to the intuition repo, or
* make translatewiki.net fetch directly from each repo and each repo/intuition "instance" to fetch translations directly from translatewiki.net, à la https://www.mediawiki.org/w/index.php?title=Outreach_programs/Possible_projects&oldid=902079#Generic.2C_efficient_Localisation_Update_service proposal .
We should figure out what the main pain point is.

**Comment by nemobis** [comment]
Interesting development! Thanks.

**Comment by Krinkle** [comment]
I'll work with translatewiki.net to figure out the necessary infrastructure to sync to/from different repos whilst still using a single project namespace (`Intuition:<domain>-`) on translatewiki.net.

Note that anyone opting into this system will most likely have to grant one or more individuals from translatewiki.net push access.

I'll migrate one of my own tools as example and report back here when it's done.

**Comment by kenrick95** [comment]
:+1:

**Comment by Krinkle** [comment]
To move messages to your own repo, follow these steps in below order.

First, make sure your project does not use any `/data/project/intuition` files on Tool Labs. Install Intuition into your project directly. See updated instructions in the [readme](https://github.com/Krinkle/intuition#readme).
 * You'll find that composer is not installed by default on the tools-login server. See [T104789](https://phabricator.wikimedia.org/T104789#1615175) for instructions.
 * For the time being, there's no need to register the domain as it is still part of the library. The switch to a local installation will ensure that in later steps (when we remove messages from the central install) your tool will continue to work with the local version.

Once your project is migrated and the update is deployed on Tool Labs, there's four steps:

1. Copy your messages directory from `intuition:/language/messages/:domain` to `your-repo:/messages`, commit, and push to your master branch on GitHub. (example: <https://github.com/Krinkle/mw-tool-orphantalk/commit/d6986d079cf73b4c7dfee7dad40a7d78e63b3186>)
2. Register your new local text domain. (example: [Krinkle/mw-tool-orphantalk](https://github.com/Krinkle/mw-tool-orphantalk/blob/d6986d079cf73b4c7dfee7dad40a7d78e63b3186/public_html/index.php#L21))
3. Register your repo at translatewiki by sending a commit such as wikimedia/translatewiki@bb2b523fb30 (<https://gerrit.wikimedia.org/r/237193>) to Gerrit for review.
4. Add @Nikerabbit and @siebrand as collaborators in your repository settings on GitHub.

That's it. Your project is now independent and will receive translatewiki.net updates directly. Make sure you [watch your repository](https://help.github.com/articles/watching-repositories/) and look for those translatewiki.net updates. Git pull on Tool Labs to deploy them.
