### ISSUE TITLE
Moving reFill back to Translatewiki

### ISSUE THREAD

**Issue by zhaofengli** [Krinkle/intuition#52]
The translation workflow of reFill (formerly Reflinks) was moved to Transifex some time ago (#42), but I'm willing to return to Translatewiki following the recent changes of Intuition. The complete source of the tool is available on [zhaofengli/refill](https://github.com/zhaofengli/refill). I've [replaced](https://github.com/zhaofengli/refill/commit/e604853778bafe80484ad717e29ad14c6a072562) my customized fork of Intuition with the Composer version, and it seems to work fine as a drop-in replacement. What are the next steps to take? How will we migerate the existing translations to Translatewiki? Thanks for your time :smile:

**Comment by nemobis** [comment]
Hi, very good to hear. I just checked https://github.com/Krinkle/intuition/wiki/Migrate and the instructions seem current, can you follow them? Let us know if you need help.

Translations will be imported from your repository to translatewiki.net upon the first sync.

**Comment by zhaofengli** [comment]
Okay, proposed at https://gerrit.wikimedia.org/r/254638. Is everything alright? However, I'm wondering how Translatewiki will handle changes to the source messages (en and qqq) in the repo.

**Comment by siebrand** [comment]
I've reviewed that patch. There's one clear issues that needs to be fixed (copy/paste omission).

**Comment by zhaofengli** [comment]
@siebrand Thanks! However, I'm not seeing your review there, only jenkins-bot's +1 which was made days ago.

**Comment by Krinkle** [comment]
@zhaofengli It's inside the file view at 
<https://gerrit.wikimedia.org/r/#/c/254638/1/groups/Intuition/refill.yaml>

**Comment by Krinkle** [comment]
Fixed as of https://github.com/zhaofengli/refill/commit/e604853778bafe80484ad717e29ad14c6a072562.
