### ISSUE TITLE
Languages with entries in fallbacks.json don't have English in their fallback chains

### ISSUE THREAD

**Issue by kaldari** [Krinkle/intuition#53]
When Intuition generates a fallback chain for a language that is listed in fallbacks.json, it only includes the languages listed in the fallback chain there. English does not get added. So, for example, the fallback chain generated for Western Balochi is just "fa", not "fa, en". This is causing broken messages when viewing http://tools.wmflabs.org/pageviews-test/ in Western Balochi.

**Comment by Krinkle** [comment]
I'm not sure that is the reason it is broken. See `Intuition::msg()` uses `Intuition::getLangForMsg()` which ultimately falls back to English (since that is currently our source language).

Adding it to the fallback registry is somewhat repetitive and should be redundant.

**Comment by kaldari** [comment]
Yes, getLangForMsg() does fall back to English, but only if no fallbacks are otherwise found. If a language does have a fallback, like de-formal or zh-hk, English is never included in its fallback chain.

**Comment by Krinkle** [comment]
Hm.. In that case please add a unit test that fails against master.

**Comment by kaldari** [comment]
Added additional test for `testMsgFallback()` that fails against current master.
