### ISSUE TITLE
Rename/drop monumentsapi

### ISSUE THREAD

**Issue by lokal-profil** [Krinkle/intuition#58]
`monumentsapi` has been migrated to using intuition as a library with the i18n messages now in https://phabricator.wikimedia.org/diffusion/THER/

Additionally the name of the domain has changed to `heritage`.

The name should either be updated here or possibly the whole domain should be removed from this repository?

**Comment by Krinkle** [comment]
Yeah, the code should be removed from this repository. I assume any translations on translatewiki have already been moved and renamed internally, there.

**Comment by lokal-profil** [comment]
Ok. I'll do a pull for that. Do you still want it in tools.json (renamed) or should I drop it from there as well?

**Comment by Krinkle** [comment]
@lokal-profil If it's still using Intuition (as a library), I'd like it to still be listed there if the maintainer(s) are okay with that.

**Comment by lokal-profil** [comment]
I removed the `title-msg` bit since I'm guessing that would look for a local message. But left the url (since I saw this solution being used elsewhere)
