### ISSUE TITLE
File not found errors if userlang=en-gb

### ISSUE THREAD

**Issue by Krinkle** [Krinkle/intuition#81]
Originally reported at <https://github.com/Krinkle/intuition-web/issues/2> by @Jarry1250 

-----

> Contrast https://tools.wmflabs.org/jarry-common/?userlang=en-gb and https://tools.wmflabs.org/jarry-common/?userlang=en.
> 
> Example error: Warning: file_get_contents(/mnt/nfs/labstore-secondary-tools-project/intuition/src/Intuition/language/messages/general/en-gb.json): failed to open stream: No such file or directory in /mnt/nfs/labstore-secondary-tools-project/intuition/src/Intuition/src/Intuition.php on line 814

**Comment by Krinkle** [comment]
@Jarry1250 This bug should be fixed by 8cd1629. It's released as part of release v0.6.1.

Can you try to upgrade and let me know if it is resolved?

**Comment by Jarry1250** [comment]
Thanks! I can't reproduce with the new version.
