### ISSUE TITLE
Intuition fails with a 502 Bad Gateway

### ISSUE THREAD

**Issue by mainframe98** [Krinkle/intuition#82]
Regardless of visiting using https://tools.wmflabs.org/intuition or directly from a tool (https://tools.wmflabs.org/intuition/?returnto=%2Fsnapshots%2Findex.php&returntoquery=#tab-settingsform).

**Comment by Matthewrbowker** [comment]
@Krinkle It's worth noting that several tools were experiencing 502s at about the same time... I mentioned it in #wikimedia-cloud on IRC and they mentioned it might be an infrastructure problem.

**Comment by Krinkle** [comment]
Yeah, I'll close this issue. Appears to have been a general service outage of the public tools proxy, not the individual tool process.
