### ISSUE TITLE
Enable translations for WPPB (Tool Labs)

### ISSUE THREAD

**Issue by tbertels** [Krinkle/intuition#85]
See https://tools.wmflabs.org/pb/index.py?p=about&
It stays in German no matter the browser language settings.

**Comment by Krinkle** [comment]
@tbertels I can reproduce the issue, but I also notice that this only happens on the "pb" tool, and not elsewhere. For example, <https://tools.wmflabs.org/guc/> and <https://tools.wmflabs.org/intuition/> render fine in my current language (not German).

I suspect this may be a problem with the code in the PB tool. I can help if I see the code. The current source code link is broken (404 Not Found; <https://github.com/tool-labs/pb>)

**Comment by tbertels** [comment]
The fact that the source code isn't available anymore is a known fact from the German FAQ. Since it's on  https://tools.wmflabs.org, it shouldn't be a problem to copy it to a new repository though.

**Comment by tbertels** [comment]
The repository is now back online at https://github.com/tool-labs/pb
But Intuition doesn't seem to be used in the code, though the strings are on translatewiki.net (for example https://translatewiki.net/wiki/Intuition:Pb-pb-about-pb-text/de). Do every extension and gadget gets its strings automatically sent to translatewiki.net?
If you know a page that explains all that, it would be great. :)

**Comment by Nikerabbit** [comment]
It's not automatic, you have to ask. You likely should migrate the strings from intuition to that repository first.

**Comment by Krinkle** [comment]
For the migration, use <https://github.com/Krinkle/intuition/wiki/Migrate> as a starting point. Feel free to ask questions here.

**Comment by tbertels** [comment]
Thanks for the help!
I just found out the strings are actually supposed to be in this intuition repository by default, and they are (at https://github.com/Krinkle/intuition/tree/master/language/messages/pb).
They just aren't currently being used in the pb project. And for a good reason: it's written in Python while there isn't yet a Python implementation of Intuition (#18). Though the current code of pb doesn't include the messages names found in https://github.com/Krinkle/intuition/blob/master/language/messages/pb/en.json Would the current code be an outdated version?

Anyway, I'd suggest adding a basic description of how Intuition works in the readme, something like:
Once you have [enabled translation in your project](https://translatewiki.net/wiki/Setup_of_a_new_project), its strings will be available for translation on translatewiki.net and will be periodically synced in the Intuition repository [language/messages](https://github.com/Krinkle/intuition/tree/master/language/messages)/[your project name] directory. These strings can then be directly [used in your project](https://github.com/Krinkle/intuition/wiki/Documentation#usage).

**Comment by Nikerabbit** [comment]
Not quite: these days the strings are supposed to be in the same repository with the source code to ensure they stay in sync. But otherwise, after registering it in translatewiki.net, it works the same.
