### ISSUE TITLE
Allow local overrides for unknown language codes

### ISSUE THREAD

**Issue by Krinkle** [Krinkle/intuition#88]
Following https://github.com/Krinkle/intuition/pull/87, it seems useful to allow individual projects to register additional language codes and translations for them, even if they are not in Intuition's Names.php file, and are not yet indexed by translatewiki.net.

**Comment by samwilson** [comment]
Good idea!

Could this be something like the addition of `Intuition::addAvailableLang()`? e.g.:
```php
    public function addAvailableLang( $code, $name )
    {
        $this->getLangNames();
        $this->langNames[$code] = $name;
        $this->availableLanguages[$code] = $name;
    }
```
